services:
  - type: web
    name: proddaem
    runtime: python
    rootDir: web
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
